version: 2
jobs:
  build:
    docker:
      - image: moiosuse/sumaform-images-circleci:1.0
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ./artifacts
      - run:
        name: Run Packer
        command: |
          mkdir output &&
          PACKER_LOG=1 packer build centos7.json &&
          mv output-centos7/centos7 output/centos7.qcow2
      - persist_to_workspace:
        root: output
        paths:
          - '*.qcow2'

  publish-github-release:
    docker:
      - image: cibuilds/github:0.12.0
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts/

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^\d+\.\d+\.\d+$/
