version: 2
jobs:
  validate:
    docker:
      - image: moiosuse/sumaform-images-circleci:2.0
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Run Packer Validation
          command: PACKER_LOG=1 packer validate centos7.json

  build:
    docker:
      - image: moiosuse/sumaform-images-circleci:2.0
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Run Packer Build
          command: |
            if [ -z "${CIRCLE_TAG:-}" ]; then
              echo "This is not a tagged version, not releasing to GitHub"
            else
              # PACKER_LOG=1 packer build centos7.json
              mkdir output
              #mv output-centos7/centos7 output/centos7.qcow2
              echo test > output/centos7.qcow2
              echo ghr -t TOKETI -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} output
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} output
            fi

workflows:
  version: 2
  on-push:
    jobs:
      - validate
  on-release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
